services:
  ewooni-docker:
    build:
      context: ..
      dockerfile: docker/jetson_test2.Dockerfile
    image: ewooni-docker:humble
    container_name: ewooni_docker_container
    network_mode: host
    ipc: host
    privileged: true
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      DISPLAY: ${DISPLAY:-}
      QT_X11_NO_MITSHM: "1"
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/workspaces/ewooni_docker
      - ../rosbags:/workspaces/ewooni_docker/rosbags
    command:
      - bash
      - -lc
      - |
        cd /workspaces/ewooni_docker && source install/setup.bash && ros2 launch eclipse_pkg tars_autonomy.launch.py
